// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace BudgetTrackerAPI.Models;

public partial class Budget
{
    public Guid BudgetId { get; set; }

    public Guid UserId { get; set; }

    public string Name { get; set; }

    public decimal Amount { get; set; }

    public string Period { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();

    public virtual User User { get; set; }
}