// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BudgetTrackerAPI.Models;

public partial class BudgetView
{
    public Guid BudgetId { get; set; }

    public string Name { get; set; }

    public decimal Budgeted { get; set; }

    public decimal Actual { get; set; }
}