// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BudgetTrackerAPI.Models;

public partial class Category
{
    public Guid CategoryId { get; set; }

    public string UserId { get; set; }

    public string Name { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}