// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BudgetTrackerAPI.Models;

public partial class Goal
{
    public Guid GoalId { get; set; }

    public Guid UserId { get; set; }

    public string Name { get; set; }

    public decimal TargetAmount { get; set; }

    public decimal? SavedAmount { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User User { get; set; }
}