// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BudgetTrackerAPI.Models;

public partial class Transaction
{
    public Guid TransactionId { get; set; }

    public string UserId { get; set; }

    public Guid CategoryId { get; set; }

    public decimal Amount { get; set; }

    public DateTime TransactionDate { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Category Category { get; set; }
}